import { chromium } from '@playwright/test';
import fs from 'fs';
import path from 'path';
import { loadHarnessConfig, AXHarnessConfig } from './config';
import { AXScenarioRunner } from './scenario-runner';
import { AXFeedbackFormatter } from '../../ax-engine/feedback-formatter';

export async function runAXHarness(command: string = 'verify', cwd: string = process.cwd(), isWatch: boolean = false) {
  console.log(`
  ╔══════════════════════════════════════════════════════╗
  ║       🩹 AX-HEAL (AI Self-Healing Test Harness)      ║
  ║    AI-to-AI Verification & Auto-Repair Gatekeeper   ║
  ╚══════════════════════════════════════════════════════╝
  `);

  if (command === 'init' || command === 'scan') {
    const { scanProjectAndGenerateConfig } = await import('./scanner.ts');
    scanProjectAndGenerateConfig(cwd);
    console.log('✅ ax.config.json auto-generated by AI Code Scanner! Run `npm run ax:heal` (or `npx ax-heal`) to execute tests.');
    return;
  }

  const config: AXHarnessConfig = loadHarnessConfig(cwd);

  console.log(`📌 Project: ${config.projectName}`);
  console.log(`🌐 Base URL: ${config.baseURL}`);
  console.log(`🧪 Scenarios Configured: ${config.scenarios.length}`);

  // Check if web app server is running, if not, auto-spawn
  let devProcess: any = null;
  const isServerRunning = await fetch(config.baseURL).then(() => true).catch(() => false);
  if (!isServerRunning && config.devCommand) {
    console.log(`📡 Base URL ${config.baseURL} is offline. Auto-starting dev server ("${config.devCommand}")...`);
    const { exec } = await import('child_process');
    devProcess = exec(config.devCommand, { cwd });
    await new Promise((resolve) => setTimeout(resolve, 4000));
  }

  const runVerificationPass = async () => {
    const formatter = new AXFeedbackFormatter();
    const browser = await chromium.launch({ headless: true });
    const page = await browser.newPage();
    const runner = new AXScenarioRunner(page, formatter);

    for (const scenario of config.scenarios) {
      try {
        await runner.executeScenario(scenario, config.outputDir || './.ax');
      } catch (err: any) {
        console.error(`❌ Scenario "${scenario.name}" FAILED!`);
        const domSnapshot = await page.content().catch(() => '');
        formatter.addFailure({
          suite: 'Stagehand',
          testName: scenario.name,
          errorMessage: err.message || 'Scenario execution failed',
          stackTrace: err.stack || String(err),
          domSnapshot,
          timestamp: new Date().toISOString(),
        });
      }
    }

    await browser.close();

    const { jsonPath, promptPath, htmlPath } = formatter.generateReport(config.outputDir || './.ax');
    console.log(`\n🎉 AX-HEAL Verification Finished!`);
    console.log(`📄 Machine Feedback: ${jsonPath}`);
    console.log(`📝 Auto-Repair Prompt: ${promptPath}`);
    console.log(`📊 HTML Visual Dashboard: ${htmlPath}\n`);
  };

  await runVerificationPass();

  if (devProcess && !isWatch) {
    devProcess.kill();
  }

  if (isWatch) {
    console.log('👀 [AX Watcher] Watching src/ and components/ for code changes...');
    const watchDir = path.join(cwd, 'src');
    if (fs.existsSync(watchDir)) {
      fs.watch(watchDir, { recursive: true }, async (eventType, filename) => {
        if (filename && /\.(tsx|ts|jsx|js|css)$/.test(filename)) {
          console.log(`\n🔄 File change detected: ${filename}. Re-executing AX-HEAL...`);
          await runVerificationPass().catch(() => {});
        }
      });
    }
  }
}
