import { chromium } from '@playwright/test';
import { loadHarnessConfig, AXHarnessConfig } from './config';
import { AXScenarioRunner } from './scenario-runner';
import { AXFeedbackFormatter } from '../../ax-engine/feedback-formatter';

export async function runAXHarness(command: string = 'verify', cwd: string = process.cwd()) {
  console.log(`
  ╔══════════════════════════════════════════════════════╗
  ║       🩹 AX-HEAL (AI Self-Healing Test Harness)      ║
  ║    AI-to-AI Verification & Auto-Repair Gatekeeper   ║
  ╚══════════════════════════════════════════════════════╝
  `);

  const config: AXHarnessConfig = loadHarnessConfig(cwd);

  if (command === 'init' || command === 'scan') {
    const { scanProjectAndGenerateConfig } = await import('./scanner.ts');
    scanProjectAndGenerateConfig(cwd);
    console.log('✅ ax.config.json auto-generated by AI Code Scanner! Run `npm run ax:heal` (or `npx ax-heal`) to execute tests.');
    return;
  }

  console.log(`📌 Project: ${config.projectName}`);
  console.log(`🌐 Base URL: ${config.baseURL}`);
  console.log(`🧪 Scenarios Configured: ${config.scenarios.length}`);

  // Check if web app server is already running, if not, spawn dev server
  let devProcess: any = null;
  const isServerRunning = await fetch(config.baseURL).then(() => true).catch(() => false);
  if (!isServerRunning && config.devCommand) {
    console.log(`📡 Base URL ${config.baseURL} is offline. Auto-starting dev server ("${config.devCommand}")...`);
    const { exec } = await import('child_process');
    devProcess = exec(config.devCommand, { cwd });
    // Wait for dev server startup
    await new Promise((resolve) => setTimeout(resolve, 3000));
  }

  const formatter = new AXFeedbackFormatter();
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage();

  const runner = new AXScenarioRunner(page);

  for (const scenario of config.scenarios) {
    try {
      await runner.executeScenario(scenario);
    } catch (err: any) {
      console.error(`❌ Scenario "${scenario.name}" FAILED!`);
      const domSnapshot = await page.content().catch(() => '');
      formatter.addFailure({
        suite: 'Stagehand',
        testName: scenario.name,
        errorMessage: err.message || 'Scenario execution failed',
        stackTrace: err.stack || String(err),
        domSnapshot,
        timestamp: new Date().toISOString(),
      });
    }
  }

  await browser.close();
  if (devProcess) {
    devProcess.kill();
  }

  const { jsonPath, promptPath } = formatter.generateReport(config.outputDir || './.ax');
  console.log(`\n🎉 Verification AX Harness Finished!`);
  console.log(`📄 Machine Feedback: ${jsonPath}`);
  console.log(`📝 Auto-Repair Prompt: ${promptPath}\n`);
}
